{% set name = "calliope" %}
{% set version = "0.6.5" %}
{% set sha256 = "ad2c6e8faf538d985e9f21a311642a519df1cd4130626ca4cfc53ca4ec591393" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  host:
    - python >=3.7,<3.9
    - pip
  run:
    - python >=3.7,<3.9
    - bottleneck >=1.2
    - click >=7,<8
    - glpk >=4.61,<4.63
    - hdf5
    - ipython >=7
    - ipdb >=0.11
    - jinja2 >=2.10
    - libnetcdf
    - natsort >=5
    - netcdf4 >=1.2.2
    - numexpr >=2.3.1
    - numpy >=1.15
    - pandas >=0.25,<0.26
    - plotly >=3.3,<4.0
    - pyomo >=5.6,<5.7
    - ruamel.yaml >=0.16
    - scikit-learn >=0.22
    - xarray >=0.14,<0.15

test:
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems modelling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
