{% set name = "calliope" %}
{% set pypi_version = "0.7.0.dev2" %}
{% set conda_version = "0.7.0dev2" %}
{% set sha256 = "5ccd00201f9e6c8c857cf32e0d64a441b60d6d61e825886673c7edec45df4cb5" %}

package:
  name: {{ name|lower }}
  version: {{ conda_version }}

source:
  fn: {{ name }}-{{ pypi_version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  host:
    - python >=3.10,<3.12
    - pip
  run:
    - python >=3.10,<3.12
    - bottleneck >=1,<2
    - click >=8,<9
    - geographiclib >=2,<3
    - hdf5 <2
    - ipdb >=0.13,<0.14
    - ipykernel <7
    - jinja2 >=3,<4
    - jsonschema >=4,<5
    - libnetcdf <5
    - natsort >=8,<9
    - netcdf4 >=1.2,<1.7
    - numpy >=1,<2
    - pandas >=2.1.3,<2.2
    - pyomo >=6.5,<7
    - pyparsing >=3.0,<3.1
    - ruamel.yaml >=0.17,<0.18
    - xarray >=2023.10,<2024.3
  run_constrained:
    - glpk >=5,<5.1

test:
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems modelling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
