{% set name = "calliope" %}
{% set version = "0.6.10" %}
{% set sha256 = "1a9d29e63063b9d0f8256337d5f8a5d08c3ba1319fc6e72f37448111676c1ee9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  host:
    - python >=3.8,<3.10
    - pip
  run:
    - python >=3.8,<3.10
    - bottleneck <=1.3
    - click >=8,<9
    - hdf5 <=1.12
    - ipython >=7
    - ipdb >=0.13
    - jinja2 >=2.10
    - libnetcdf <=4.8
    - natsort >=5
    - netcdf4 >=1.2.2
    - numpy >=1.23,<1.24
    - pandas >=1.5,<1.6
    - plotly >=3.10,<3.11
    - pyomo >=6.4,<6.5
    - ruamel.yaml >=0.17,<0.18
    - scikit-learn >=1.2,<1.3
    - xarray >=2022.3,<2022.4
  run_constrained:
    - glpk >=5,<5.1

test:
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems modelling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
