{% set name = "calliope" %}
{% set version = "0.5.5" %}
{% set md5 = "cd8a949a23041132eef72b3e152248e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<36 or py>36]
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.6
    - basemap
    - basemap-data-hires  # Otherwise we get an error on calling some plotting funcs
    - bottleneck
    - click >=3.3
    - descartes
    - glpk >=4.61
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - matplotlib >=2.0
    - netcdf4 >=1.2.2
    - networkx
    - numexpr >=2.3.1
    - numpy >=1.12
    - pandas >=0.19.2,<0.20
    - pyomo >=5.2,<5.3
    - ruamel.yaml <=0.15
    - scipy
    - seaborn
    - shapely
    - xarray >=0.9.5,<0.10

test:
  imports:
    - calliope
    - calliope.analysis
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems (MUSES) modeling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
