{% set name = "calliope" %}
{% set version = "0.5.0" %}
{% set md5 = "b7d4c13e60cddaf6a5b6321ee92cf5fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # No py36 version yet: basemap, pyomo
  skip: True  # [py<35 or py>35]
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.5
    - basemap
    - bottleneck
    - click >=3.3
    - descartes
    - glpk ==4.59
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
    - matplotlib >=2.0
    - netcdf4 >=1.2.2
    - networkx
    - numexpr >=2.3.1
    - numpy >=1.2
    - pandas >=0.19.2,<0.20
    - pyomo >=5.0,<5.1
    - pyyaml >=3.11
    - scipy
    - seaborn
    - shapely
    - xarray >=0.9.5,<0.10

test:
  imports:
    - calliope
    - calliope.analysis
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems (MUSES) modeling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
