{% set name = "calliope" %}
{% set version = "0.6.1" %}
{% set sha256 = "d7c7e53247b6fb0b3439ca4948239a38423e9f020f112fb6c6eedb189ee23b66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<36 or py>36]
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.6
    - bottleneck
    - click >=3.3
    - cufflinks-py >=0.12.1
    - glpk >=4.61
    - hdf5 1.8.18|1.8.18.*
    - ipython >=6.2.1
    - libnetcdf 4.4.*
    - natsort >=5.2
    - netcdf4 >=1.2.2
    - numexpr >=2.3.1
    - numpy >=1.14
    - pandas >=0.22,<0.23
    - plotly >=2.5
    - pyomo >=5.4,<5.5
    - ruamel.yaml <=0.15
    - scikit-learn >=0.19.1
    - xarray >=0.10.0,<0.11

test:
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems (MUSES) modeling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
