{% set name = "calliope" %}
{% set pypi_version = "0.7.0.dev5" %}
{% set conda_version = "0.7.0dev5" %}
{% set sha256 = "ba83a13a191f52c936732176717312a20111c597b4a95bb8526c1b1825f84f4d" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ conda_version }}

source:
  fn: {{ name }}-{{ pypi_version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck >=1,<2
    - click >=8,<9
    - geographiclib >=2,<3
    - hdf5 <2
    - ipdb >=0.13,<0.14
    - ipykernel <7
    - jinja2 >=3,<4
    - jsonschema >=4,<5
    - libnetcdf <5
    - natsort >=8,<9
    - netcdf4 >=1.2,<1.7
    - numpy >=1,<2
    - pandas >=2.1.3,<2.3
    - pyomo >=6.8.2,<7
    - pyparsing >=3.0,<3.1
    - ruamel.yaml >=0.18,<0.19
    - xarray >=2024.1,<2024.4
  run_constrained:
    - glpk >=5,<5.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems modelling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
