{% set name = "calliope" %}
{% set version = "0.6.3" %}
{% set sha256 = "6423bb66063d0d27c3c0d0b4791723a94f29e4075316ab29338e98de2e60e59b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - calliope = calliope.cli:cli

requirements:
  host:
    - python >=3.6,<3.8
    - pip
  run:
    - python >=3.6,<3.8
    - bottleneck
    - click >=3.3,<7
    - glpk >=4.61
    - hdf5 1.8.18|1.8.18.*
    - ipython >=6.2.1
    - libnetcdf 4.4.*
    - natsort >=5.2
    - netcdf4 >=1.2.2
    - numexpr >=2.3.1
    - numpy >=1.14
    - pandas >=0.22,<0.23
    - plotly >=3.3
    - pyomo >=5.4,<5.5
    - ruamel.yaml >=0.15.71,<0.16
    - scikit-learn >=0.19.1
    - xarray >=0.10.8,<0.11

test:
  imports:
    - calliope
  commands:
    - calliope --help

about:
  home: https://www.callio.pe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A multi-scale energy systems modelling framework
  description: |
    Calliope is a framework to develop energy system models, with a
    focus on flexibility, high spatial and temporal resolution, the
    ability to execute many runs based on the same base model, and
    a clear separation of framework (code) and model (data).
  doc_url: https://calliope.readthedocs.io/
  dev_url: https://github.com/calliope-project/calliope

extra:
  recipe-maintainers:
    - sjpfenninger
    - brynpickering
