travis:
  secure:
    BINSTAR_TOKEN: bYjZIQyO4JjM041FHO3BF3HdFCIBk1/Y3od+OgIG4i+n6Jn+D25aIeDHIhIRR4gOnzxdca5fQbmQggSIHp4bMOfVbVtiKzfrWQegJVU9IIDM6WFNd4+ql1IooYOVCQbJx0om4lbjKSeRNUHqcOIQ8mX5nu5DCJNQj5CAjrp27GPRQP6KdL6Dt2eh3Nucn2NeI57Yy3BUrHcgFeWpfF8X5Y+ceou94XbtyUTR4YmFS07M98kW0AZtMXvPxuCP+hEGVoQfJ8JWN6D6kNJLYPegb3B8BmGSXDWYXOURdahCe6nuUJWgF9/WSl7139EDA6LCzzFGsRM0KA7j2DadFTZU/kjn94N910Ss7LSk9UsEZ+B1Me+zIqRrBy627FxYxUQg/juL5dWyB9tZOcDF9Iux0n04O6ZbricSVIfL0vFRdxRrXtpBUdi08DmTQRVIo5nZpYLU3vScH6QXKH23/kWKHzzN3DWDSFWJxjtTd2DVG+hgtUfHa3q9en01gO42G6y2cifsAhia9FHH4ipHa1UJsc/1M4LCyK9zDcUbhRcydlMHj+R49a59NslwaQmB3pYMRDT7d6NJMLXKoRmDcH5Ph6tKJgZ/AsyO7pPFIFj5nJ46Jac8p5y5EzgCgJmnhspDhzaAMozTxOhrBVm1HgQAMBd98U78AOb+GdvljcWqES0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
